## --------------------------------------------------------------------------------------------------------------------------------------------
#| label: setup
#| include: false

library(dplyr)
library(tidyr)
library(ggplot2)
library(patchwork)
library(scales)
library(knitr)

# ── Load & combine all result files ──────────────────────────────────────────
res_dir <- "~/2026_fedGee/simulations/sim_results"

files <- sprintf(file.path(res_dir, "results_%04d.rds"), 1:300)
exist <- file.exists(files)

all_res <- bind_rows(lapply(files[exist], readRDS))

# Drop any ERROR rows
all_res <- all_res |> filter(method != "ERROR")


## --------------------------------------------------------------------------------------------------------------------------------------------
#| label: fig-sim-bias
#| fig-cap: "**Point Estimation and Bias in Federated vs. Traditional Networks.** All panels use $K = 25$ and $\\beta_0 = -1$ (common outcome) unless otherwise noted. **(A)** Mean absolute bias heatmap of FedGEE vs. Meta-Analytic GLM across the full $\\rho_H \\times \\rho_P$ grid, illustrating the degradation of traditional meta-analysis as between-hospital correlation grows. **(B)** Mean absolute bias under a rare outcome ($\\beta_0 = -3$), demonstrating the robustness of the federated Newton-Raphson update when local site data is sparse. **(C)** Histogram of the site-level covariate estimates ($\\hat{\\beta}_{\\text{teach}}$) generated by FedGEE, showing the algorithm's ability to accurately recover site-constant effects strictly from between-site variation. **(D)** Scatterplot establishing mathematical parity: FedGEE coefficient estimates plotted directly against Centralized Pooled GEE estimates. The maximum absolute difference across all replications in this scenario is annotated."
#| fig-width: 14
#| fig-height: 11
#| echo: false
#| warning: false
#| message: false

# ── Shared heatmap builder for Panels A & B ──────────────────────────────────
build_bias_heatmap <- function(data, b0, panel_label, panel_subtitle) {
  
  hm_dat <- data |>
    filter(beta_0 == b0, K == 25,
           include_teaching == FALSE,
           method %in% c("fed_site", "meta_glm"),
           !is.na(bias)) |>
    group_by(rho_H, rho_P, method) |>
    summarise(mean_abs_bias = mean(abs(bias)), .groups = "drop") |>
    mutate(
      method = recode(method,
                      fed_site = "FedGEE",
                      meta_glm = "Meta-Analytic GEE"),
      rho_H = factor(rho_H),
      rho_P = factor(rho_P)
    )
  
  ggplot(hm_dat, aes(x = rho_P, y = rho_H, fill = mean_abs_bias)) +
    geom_tile(colour = "white", linewidth = 0.4) +
    geom_text(aes(label = sprintf("%.2f", mean_abs_bias)),
              size = 4, colour = "black") +
    facet_wrap(~ method) +
    scale_fill_distiller(palette = "YlOrRd", direction = 1,
                         name = "Mean |Bias|") +
    labs(x = expression(rho[P]),
         y = expression(rho[H]),
         title = bquote(bold(.(panel_label)) ~ .(panel_subtitle))) +
    theme_bw(base_size = 12) +
    theme(plot.title       = element_text(size = 12),
          legend.position  = "bottom",
          legend.key.width = unit(1.2, "cm"),
          panel.grid       = element_blank(),
          strip.background = element_rect(fill = "grey92"),
          strip.text       = element_text(face = "bold"))
}

# ── Panel A: Common outcome heatmap ──────────────────────────────────────────
panel_a <- build_bias_heatmap(all_res, b0 = -1,
                               panel_label = "A",
                               panel_subtitle = "Common outcome, true parameter = 1, K = 25")

# ── Panel B: Rare outcome heatmap ────────────────────────────────────────────
panel_b <- build_bias_heatmap(all_res, b0 = -3,
                               panel_label = "B",
                               panel_subtitle = "Rare outcome, true parameter = 1, K = 25")

# ── Panel C: Histogram of beta_teach estimates (K = 25, β₀ = −1) ─────────────
teach_hat <- all_res |>
  filter(include_teaching == TRUE,
         method == "fed_site",
         K == 25, beta_0 == -1,
         !is.na(beta_teach_hat))

true_teach <- 0.5

panel_c <- ggplot(teach_hat, aes(x = beta_teach_hat)) +
  geom_histogram(aes(y = after_stat(density)),
                 bins = 50, fill = "#2166AC", colour = "white", alpha = 0.8) +
  geom_vline(xintercept = true_teach, linetype = "dashed",
             colour = "#B2182B", linewidth = 0.9) +
  annotate("text", x = true_teach, y = Inf,
           label = paste0("True = ", true_teach),
           hjust = -0.15, vjust = 1.5, colour = "#B2182B", size = 6) +
  labs(x = expression(hat(beta)[teach]),
       y = "Density",
       title = expression(bold("C") ~ " Recovery of site-level covariate (K = 25, true " * beta * " = 1)")) +
  theme_bw(base_size = 12) +
  theme(plot.title = element_text(size = 12))

# ── Panel D: FedGEE vs Pooled GEE parity scatterplot (K = 25, β₀ = −1) ──────
parity <- all_res |>
  filter(method %in% c("fed_site", "pooled_gee"),
         K == 25, beta_0 == -1,
         !is.na(beta_hat)) |>
  select(rho_H, rho_P, K, beta_0, include_teaching, rep, method, beta_hat) |>
  pivot_wider(names_from = method, values_from = beta_hat) |>
  filter(!is.na(fed_site), !is.na(pooled_gee))

max_diff <- max(abs(parity$fed_site - parity$pooled_gee))

panel_d <- ggplot(parity, aes(x = pooled_gee, y = fed_site)) +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed",
              colour = "#B2182B", linewidth = 0.6) +
  geom_point(alpha = 0.15, size = 0.4, colour = "#2166AC") +
  annotate("text", x = -Inf, y = Inf,
           label = sprintf("Max |diff| = %.1e", max_diff),
           hjust = -0.08, vjust = 1.5, size = 6, colour = "#B2182B") +
  labs(x = expression("Pooled GEE" ~ hat(beta)[X]),
       y = expression("FedGEE" ~ hat(beta)[X]),
       title = expression(bold("D") ~ "  Mathematical parity (K = 25, true " * beta * " = 1)")) +
  theme_bw(base_size = 12) +
  theme(plot.title = element_text(size = 12))

# ── Compose (equal panel widths & heights) ───────────────────────────────────
fig1 <- (panel_a | panel_b) / (panel_c | panel_d) +
  plot_layout(heights = c(1, 1), widths = c(1, 1)) &
  theme(legend.position = "bottom")

factor <- 1.25
ggsave("fig1.pdf", 
       fig1, 
       height = factor*8.5, 
       width = factor*11, 
       units = "in", 
       device = cairo_pdf)

factor <- 1.25
ggsave("fig1.eps", 
       fig1, 
       height = factor*8.5, 
       width = factor*11, 
       units = "in", 
       device = cairo_ps)


## --------------------------------------------------------------------------------------------------------------------------------------------
#| label: tbl-sim-coverage
#| tbl-cap: "Performance of Variance Estimators by Number of Network Sites ($K$). Coverage probabilities and Standard Error to Empirical Standard Deviation (SE/SD) ratios are shown for varying sandwich architectures and small-sample corrections within the FedGEE framework. Target coverage is 0.950; target SE/SD ratio is 1.00. *Note*: Values reflect simulations where $\\rho_H > 0$. Patient-level sandwich assumes independence between patients. The SE/SD ratio is identical for the site-level $z$ and $t$ rows (same standard error estimate; only the critical value differs) and is reported once. MD = Mancl-DeRouen correction."
#| echo: false
#| warning: false
#| message: false

# ── Patient-level sandwich (z-based) ────────────────────────────────────────
tbl_patient <- all_res |>
  filter(rho_H > 0, method == "fed_patient",
         !is.na(beta_hat), !is.na(se_hat), !is.na(covers_z)) |>
  group_by(K) |>
  summarise(
    cov_patient  = mean(covers_z),
    sesd_patient = mean(se_hat) / sd(beta_hat),
    .groups = "drop"
  )

# ── Site-level sandwich, z-based (fed_site) ──────────────────────────────────
tbl_site_z <- all_res |>
  filter(rho_H > 0, method == "fed_site",
         !is.na(beta_hat), !is.na(se_hat), !is.na(covers_z)) |>
  group_by(K) |>
  summarise(
    cov_site_z  = mean(covers_z),
    sesd_site   = mean(se_hat) / sd(beta_hat),
    .groups = "drop"
  )

# ── Site-level sandwich, t-based (fed_site) ──────────────────────────────────
tbl_site_t <- all_res |>
  filter(rho_H > 0, method == "fed_site",
         !is.na(beta_hat), !is.na(se_hat), !is.na(covers_t)) |>
  group_by(K) |>
  summarise(
    cov_site_t = mean(covers_t),
    .groups = "drop"
  )

# ── Site-level + MD correction, t-based (fed_site_md) ────────────────────────
tbl_md <- all_res |>
  filter(rho_H > 0, method == "fed_site_md",
         !is.na(beta_hat), !is.na(se_hat), !is.na(covers_t)) |>
  group_by(K) |>
  summarise(
    cov_md  = mean(covers_t),
    sesd_md = mean(se_hat) / sd(beta_hat),
    .groups = "drop"
  )

# ── Combine ──────────────────────────────────────────────────────────────────
tbl_final <- tbl_patient |>
  left_join(tbl_site_z, by = "K") |>
  left_join(tbl_site_t, by = "K") |>
  left_join(tbl_md,     by = "K") |>
  arrange(K)

# ── Format for display ──────────────────────────────────────────────────────
tbl_display <- tbl_final |>
  transmute(
    `$K$`                                        = K,
    `Patient Sandwich<br>Coverage`               = sprintf("%.3f", cov_patient),
    `Patient Sandwich<br>SE/SD`                  = sprintf("%.2f", sesd_patient),
    `Site Sandwich ($z$)<br>Coverage`             = sprintf("%.3f", cov_site_z),
    `Site Sandwich<br>SE/SD`                      = sprintf("%.2f", sesd_site),
    `Site Sandwich ($t$)<br>Coverage`             = sprintf("%.3f", cov_site_t),
    `Site + MD ($t$)<br>Coverage`                 = sprintf("%.3f", cov_md),
    `Site + MD ($t$)<br>SE/SD`                    = sprintf("%.2f", sesd_md)
  )

kable(tbl_display, align = c("l", rep("c", 7)), escape = FALSE)

