# Stat Med Tables 1-2 and Web Tables S3-S4 from the centralized simulation (sim_v3).
# Per scenario, no averaging.
#   Main Tables 1-2: VA-aligned scenarios (beta_0 = -1; largest p per K; all CVs).
#   Web Tables S3-S4: all 117 scenarios.
# Run from inst/simulations/centralized:   Rscript code/make_statmed_tables_v2.R
# If the raw output (output/fedgee_v3_all.rds, not in the repository) is present,
# the per-scenario summary is recomputed from it and saved to results/.
# Otherwise the tracked summary results/statmed_scenario_table.rds is used.
suppressPackageStartupMessages(library(dplyr))
RAW <- "output/fedgee_v3_all.rds"
SUMMARY <- "results/statmed_scenario_table.rds"
TEX_OUT <- "../../manuscript/tables/supp_sim_tables.tex"
f3 <- function(x) sprintf("%.3f", x)
## blank row (\addlinespace) before each new group of rows; g: group key per row
gap <- function(g) c(FALSE, g[-1] != g[-length(g)])
## longtable stretched to the text width
lt_open <- function(cols) paste0("\\setlength{\\LTleft}{0pt}\\setlength{\\LTright}{0pt}\\setlength{\\LTcapwidth}{\\textwidth}\n",
  "\\begin{longtable}{@{\\extracolsep{\\fill}}", cols, "@{}}\n")
if (file.exists(RAW)) {
d <- readRDS(RAW) |> filter(coef == "x", variant != "diag")
keys <- c("K", "p_extra", "beta_0", "site_size_dist")
f <- d |> filter(estimator == "fed")
cv <- function(v, i, nm) f |> filter(variant == v, inference == i) |> group_by(across(all_of(keys))) |>
  summarise(!!nm := mean(covers, na.rm = TRUE), .groups = "drop")
dfb <- f |> filter(variant == "kc", inference == "t_bm") |> group_by(across(all_of(keys))) |>
  summarise(nu = median(df, na.rm = TRUE), .groups = "drop")
dff <- f |> filter(variant == "fg", inference == "t_fgdf") |> group_by(across(all_of(keys))) |>
  summarise(nu_fg = median(df, na.rm = TRUE), .groups = "drop")
sesd <- f |> filter(inference == "z", variant %in% c("site","kc","md","fg")) |> group_by(across(all_of(keys)), variant) |>
  summarise(r = mean(se, na.rm = TRUE) / sd(beta_hat, na.rm = TRUE), .groups = "drop") |>
  tidyr::pivot_wider(names_from = variant, values_from = r, names_prefix = "sesd_")
meta <- d |> filter((estimator == "fed" & variant == "kc" & inference == "t_bm") | estimator == "meta_gee") |>
  mutate(m = ifelse(estimator == "fed", "fed", "meta")) |> group_by(across(all_of(keys)), m) |>
  summarise(cov = mean(covers, na.rm = TRUE), bsd = (mean(beta_hat, na.rm = TRUE) - 1) / sd(beta_hat, na.rm = TRUE),
            rmse = sqrt(mean((beta_hat - 1)^2, na.rm = TRUE)), ssd = mean(se, na.rm = TRUE) / sd(beta_hat, na.rm = TRUE), .groups = "drop") |>
  tidyr::pivot_wider(names_from = m, values_from = c(cov, bsd, rmse, ssd))
all <- Reduce(function(a, b) left_join(a, b, by = keys), list(
  cv("site","z","u_z"), cv("site","t_bm","u_bm"), cv("kc","t_k1","kc_k1"), cv("kc","t_kp","kc_kp"),
  cv("kc","t_bm","kc_bm"), cv("md","t_bm","md_bm"), cv("fg","t_bm","fg_bm"), cv("fg","t_fgdf","fg_fg"),
  cv("kc","t_nu","kc_nu"), dfb, dff, sesd, meta)) |>
  mutate(p = p_extra + 2, prev = c("-3" = "0.07", "-1" = "0.30", "0" = "0.50")[as.character(beta_0)],
         CV = c(uniform = "0.30", cv078 = "0.78", cv100 = "1.00")[site_size_dist],
         site_size_dist = factor(site_size_dist, c("uniform","cv078","cv100"))) |>
  arrange(K, p, desc(beta_0), site_size_dist)
saveRDS(all, SUMMARY)
} else {
  message("Raw output not found; using ", SUMMARY)
  all <- readRDS(SUMMARY)
}
va <- all |> filter(beta_0 == -1) |> group_by(K) |> filter(p == max(p)) |> ungroup()
cat("%% MAIN Table 1\n")
for (r in seq_len(nrow(va))) with(va[r, ], { b <- f3(c(u_z, u_bm, kc_k1, kc_kp, kc_bm, md_bm, fg_bm))
  cat(sprintf("%s & %s & %s & %s & %.1f\\\\\n",
  if (site_size_dist == "uniform") K else "", if (site_size_dist == "uniform") p else "", CV,
  paste(b, collapse = " & "), nu)) })
cat("%% MAIN Table 2\n")
for (r in seq_len(nrow(va))) with(va[r, ], cat(sprintf("%s & %s & %s & %s & %.2f & %s & & %s & %.2f & %s\\\\\n",
  if (site_size_dist == "uniform") K else "", if (site_size_dist == "uniform") p else "", CV,
  f3(cov_fed), bsd_fed, f3(ssd_fed), f3(cov_meta), bsd_meta, f3(ssd_meta))))
# supplement longtables
sink(TEX_OUT)
cat("% Generated by inst/simulations/centralized/code/make_statmed_tables_v2.R -- do not edit by hand.\n")
cat(lt_open("rrrrcccccccccrr"), "\\caption{Coverage of nominal 95\\% intervals for $\\beta_x$ in all 117 scenarios. Each scenario had 1{,}000 replicates; Monte Carlo standard error about 0.007.}\\label{tab:S_cov}\\\\\n\\toprule\n",
    "& & & & \\multicolumn{2}{c}{Uncorrected} & \\multicolumn{3}{c}{KC} & \\multicolumn{2}{c}{FG} & MD & KC & & \\\\\n\\cmidrule(lr){5-6}\\cmidrule(lr){7-9}\\cmidrule(lr){10-11}\n",
    "$K$ & $p$ & Prev. & CV & $z$ & $t_{\\mathrm{BM}}$ & $t_{K-1}$ & $t_{K-p}$ & $t_{\\mathrm{BM}}$ & $t_{\\mathrm{BM}}$ & $t_{\\mathrm{FG}}$ & $t_{\\mathrm{BM}}$ & $t_{\\nu}$ & $\\nu^{\\mathrm{BM}}$ & $\\nu^{\\mathrm{FG}}$\\\\\n\\midrule\n\\endfirsthead\n",
    "\\toprule\n$K$ & $p$ & Prev. & CV & $z$ & $t_{\\mathrm{BM}}$ & $t_{K-1}$ & $t_{K-p}$ & $t_{\\mathrm{BM}}$ & $t_{\\mathrm{BM}}$ & $t_{\\mathrm{FG}}$ & $t_{\\mathrm{BM}}$ & $t_{\\nu}$ & $\\nu^{\\mathrm{BM}}$ & $\\nu^{\\mathrm{FG}}$\\\\\n\\midrule\n\\endhead\n\\bottomrule\n\\endfoot\n", sep = "")
sp <- gap(paste(all$K, all$p))
for (r in seq_len(nrow(all))) with(all[r, ], { b <- f3(c(u_z, u_bm, kc_k1, kc_kp, kc_bm, fg_bm, fg_fg, md_bm, kc_nu))
  if (sp[r]) cat("\\addlinespace\n")
  cat(sprintf("%d & %d & %s & %s & %s & %.1f & %.1f\\\\\n", K, p, prev, CV, paste(b, collapse = " & "), nu, nu_fg)) })
cat("\\end{longtable}\n\n")
cat(lt_open("rrrrcccccccc"), "\\caption{Standard-error calibration (SE/SD) by variance estimator, and Fed-GEE (KC with $t_{\\mathrm{BM}}$) compared with meta-analytic GEE, in all 117 scenarios.}\\label{tab:S_sesd}\\\\\n\\toprule\n",
    "& & & & \\multicolumn{4}{c}{SE/SD} & \\multicolumn{2}{c}{Fed-GEE} & \\multicolumn{2}{c}{Meta-analytic GEE}\\\\\n\\cmidrule(lr){5-8}\\cmidrule(lr){9-10}\\cmidrule(lr){11-12}\n",
    "$K$ & $p$ & Prev. & CV & Unc. & KC & MD & FG & Cov. & Bias/SD & Cov. & Bias/SD\\\\\n\\midrule\n\\endfirsthead\n",
    "\\toprule\n$K$ & $p$ & Prev. & CV & Unc. & KC & MD & FG & Cov. & Bias/SD & Cov. & Bias/SD\\\\\n\\midrule\n\\endhead\n\\bottomrule\n\\endfoot\n", sep = "")
for (r in seq_len(nrow(all))) with(all[r, ], cat(if (sp[r]) "\\addlinespace\n", sprintf("%d & %d & %s & %s & %s & %s & %s & %s & %s & %.2f & %s & %.2f\\\\\n",
  K, p, prev, CV, f3(sesd_site), f3(sesd_kc), f3(sesd_md), f3(sesd_fg), f3(cov_fed), bsd_fed, f3(cov_meta), bsd_meta), sep = ""))
cat("\\end{longtable}\n")
sink()
# numbers for text (ranges over scenarios, no averaging)
rg <- function(x) sprintf("%.3f-%.3f", min(x), max(x))
cat("\n%% ranges over 117 scenarios\n")
cat("u_z", rg(all$u_z), "below.93", sum(all$u_z < .93), "\n")
cat("u_bm", rg(all$u_bm), "\n"); cat("kc_bm", rg(all$kc_bm), "below.93", sum(all$kc_bm<.93), "\n")
cat("kc_k1", rg(all$kc_k1), "; kc_kp", rg(all$kc_kp), "; md_bm", rg(all$md_bm), "\n")
for (b in c(-3,-1,0)) cat("kc_bm prev", b, rg(all$kc_bm[all$beta_0==b]), "\n")
cat("sesd_site", rg(all$sesd_site), " sesd_kc", rg(all$sesd_kc), " sesd_md", rg(all$sesd_md), "\n")
cat("meta cov", rg(all$cov_meta), " fed cov", rg(all$cov_fed), " meta bsd", rg(all$bsd_meta), " fed bsd", rg(all$bsd_fed), "\n")
cat("fg-kc max abs cov diff", max(abs(all$fg_bm-all$kc_bm)), "\n")
print(as.data.frame(va |> select(K,p,CV,u_z,kc_bm,kc_k1,kc_kp,nu,sesd_site,sesd_kc)), digits=3)
