# Web Appendix I tables (Web Tables S1-S2) from the decentralized simulation (v4).
# Per scenario, no averaging.
# Run from inst/simulations/decentralized:   Rscript code/make_dec_tables.R
# If the raw output (output/sim_results_v4/, not in the repository) is present,
# the per-scenario summary is recomputed from it and saved to results/.
# Otherwise the tracked summary results/dec_v4_summary.rds is used.
# The spectral quantities rho depend only on the network and are always recomputed.
suppressPackageStartupMessages(library(dplyr))
RAW_DIR <- "output/sim_results_v4"
SUMMARY <- "results/dec_v4_summary.rds"
TEX_OUT <- "../../manuscript/tables/supp_dec_tables.tex"
env <- new.env(); sys.source("code/01_decentralized_fedgee.R", envir = env)
part <- function(K, size = 5) { rid <- rep(seq_len(max(1, ceiling(K / size))), each = size, length.out = K)
  list(region_id = rid, hub_sites = vapply(unique(rid), function(r) which(rid == r)[1], integer(1))) }
Wof <- function(K, s) { w <- if (s == "visn") { pt <- part(K); env$build_weight_matrix(K, structure = "visn", region_id = pt$region_id, hub_sites = pt$hub_sites) }
  else if (s == "ring") env$build_weight_matrix(K, structure = "ring", K_neigh = 2)
  else if (s == "hub") env$build_weight_matrix(K, structure = "hub", hub = 1)
  else env$build_weight_matrix(K, structure = "complete"); if (is.list(w)) w$W else w }
rho <- function(W) sort(abs(eigen(W, symmetric = TRUE, only.values = TRUE)$values), decreasing = TRUE)[2]
Ks <- c(5, 10, 15, 25, 50, 100); nets <- c("complete", "visn", "ring", "hub")
invisible(capture.output(R <- suppressMessages(outer(Ks, nets, Vectorize(function(K, s) rho(Wof(K, s))))), type = "output"))
dimnames(R) <- list(Ks, nets)
if (dir.exists(RAW_DIR)) {
  d <- bind_rows(lapply(list.files(RAW_DIR, full.names = TRUE), readRDS))
  keys <- c("K", "rho_H", "beta_0", "include_teaching")
  m <- c(fed_site = "cen", dec_complete = "complete", dec_visn = "visn", dec_ring = "ring", dec_hub = "hub")
  s <- d |> filter(method %in% names(m)) |> mutate(net = m[method]) |> group_by(across(all_of(keys)), net) |>
    summarise(cov = mean(covers_t, na.rm = TRUE), sesd = mean(se_hat, na.rm = TRUE) / sd(beta_hat, na.rm = TRUE),
              bsd = mean(bias, na.rm = TRUE) / sd(beta_hat, na.rm = TRUE), n = n(), .groups = "drop")
  w <- tidyr::pivot_wider(s, id_cols = c(all_of(keys)), names_from = net, values_from = c(cov, sesd, bsd, n)) |>
    arrange(K, include_teaching, rho_H, desc(beta_0))
  saveRDS(list(rho = R, table = w), SUMMARY)
} else {
  message("Raw output not found; using ", SUMMARY)
  w <- readRDS(SUMMARY)$table
}
f3 <- function(x) sprintf("%.3f", x)
sink(TEX_OUT)
cat("% Generated by inst/simulations/decentralized/code/make_dec_tables.R -- do not edit by hand.\n")
cat("\\begin{table}[ht]\n\\centering\n\\caption{Second-largest eigenvalue modulus $\\rho$ of the mixing matrix, and $\\rho^{50}$, for each network and number of sites $K$.}\n\\label{tab:S_rho}\n\\footnotesize\n\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}}rcccccccc}\n\\toprule\n",
    "& \\multicolumn{2}{c}{Complete} & \\multicolumn{2}{c}{Regional} & \\multicolumn{2}{c}{Ring} & \\multicolumn{2}{c}{Hub}\\\\\n",
    "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}\\cmidrule(lr){8-9}\n$K$ & $\\rho$ & $\\rho^{50}$ & $\\rho$ & $\\rho^{50}$ & $\\rho$ & $\\rho^{50}$ & $\\rho$ & $\\rho^{50}$\\\\\n\\midrule\n", sep = "")
for (k in seq_along(Ks)) { r <- R[k, ]; r[r < 1e-10] <- 0
  cat(Ks[k], paste(sprintf("%.3f & %.3f", r, r^50), collapse = " & "), sep = " & "); cat("\\\\\n") }
cat("\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n")
cat("{\\footnotesize\\setlength{\\tabcolsep}{3pt}\\setlength{\\LTleft}{0pt}\\setlength{\\LTright}{0pt}\\setlength{\\LTcapwidth}{\\textwidth}\n\\begin{longtable}{@{\\extracolsep{\\fill}}rrrccccccccccc@{}}\n\\caption{Coverage of nominal 95\\% $t_{K-p}$ intervals and SE/SD for $\\beta_x$, centralized Fed-GEE and decentralized Fed-GEE with $L=50$ consensus rounds, by scenario. Uncorrected site sandwich throughout.}\\label{tab:S_dec}\\\\\n\\toprule\n",
    "& & & & \\multicolumn{5}{c}{Coverage} & \\multicolumn{5}{c}{SE/SD}\\\\\n\\cmidrule(lr){5-9}\\cmidrule(lr){10-14}\n",
    "$K$ & $\\rho_H$ & Prev. & $p$ & Cen. & Comp. & Reg. & Ring & Hub & Cen. & Comp. & Reg. & Ring & Hub\\\\\n\\midrule\n\\endfirsthead\n",
    "\\toprule\n$K$ & $\\rho_H$ & Prev. & $p$ & Cen. & Comp. & Reg. & Ring & Hub & Cen. & Comp. & Reg. & Ring & Hub\\\\\n\\midrule\n\\endhead\n\\bottomrule\n\\endfoot\n", sep = "")
sp <- c(FALSE, diff(w$K) != 0 | diff(w$include_teaching) != 0)  # blank row between (K, p) groups
for (r in seq_len(nrow(w))) with(w[r, ], cat(if (sp[r]) "\\addlinespace\n", sprintf("%d & %.1f & %s & %d & %s & %s & %s & %s & %s & %s & %s & %s & %s & %s\\\\\n",
  K, rho_H, ifelse(beta_0 == -3, "0.07", "0.30"), ifelse(include_teaching, 3L, 2L),
  f3(cov_cen), f3(cov_complete), f3(cov_visn), f3(cov_ring), f3(cov_hub),
  f3(sesd_cen), f3(sesd_complete), f3(sesd_visn), f3(sesd_ring), f3(sesd_hub)), sep = ""))
cat("\\end{longtable}\n}\n")
sink()
cat("reps range:", range(unlist(w[grep("^n_", names(w))])), "\n")
cat("max |cov_complete - cov_cen|:", max(abs(w$cov_complete - w$cov_cen)), " visn:", max(abs(w$cov_visn - w$cov_cen)), "\n")
cat("hub K=100 cov range:", range(w$cov_hub[w$K == 100]), " sesd:", range(w$sesd_hub[w$K == 100]), " bsd:", range(w$bsd_hub[w$K == 100]), "\n")
cat("hub K=50 cov range:", range(w$cov_hub[w$K == 50]), "; ring K=100:", range(w$cov_ring[w$K == 100]), "; cen K=100:", range(w$cov_cen[w$K==100]), "\n")
cat("hub K<=25 max|diff|:", max(abs(w$cov_hub - w$cov_cen)[w$K <= 25]), "\n")
