# Web Table S5: VHA application sensitivity (variance correction and reference distribution).
# Run from inst/application:   Rscript make_supp_va_table.R
# Input: results/2026_09_27_visn_estimates_long.csv (coefficient-level output of visn_analysis.R).
e <- read.csv("results/2026_09_27_visn_estimates_long.csv")
g <- function(v, i) { x <- e[e$variant == v & e$inference == i, ]; x[match(names(lab), x$term), ] }
## rows grouped and ordered as in the forest plot (visn_forest.R)
lab <- c(female1 = "\\quad Female", age651 = "\\quad Age $\\ge$65 years",
  auditc_low1 = "\\quad AUDIT-C no or low use", oud1 = "\\quad Opioid use disorder",
  can_high1 = "\\quad CAN score $\\ge$60th percentile",
  frail1 = "\\quad Frailty, mild or worse", icu_any1 = "\\quad Any ICU stay",
  psych1 = "\\quad Psychiatry discharging service",
  consult31 = "\\qquad Clinician", consult32 = "\\qquad Non-clinician",
  ama1 = "\\quad Discharge against advice")
grp <- c(female1 = "Demographics", auditc_low1 = "Alcohol severity", can_high1 = "Medical complexity",
  psych1 = "Hospital process")
sub <- c(consult31 = "\\quad Addiction consult")
ci <- function(x) sprintf("%.2f, %.2f", x$CI_low, x$CI_high)
A <- g("site","z"); B <- g("site","t_bm"); C <- g("kc","t_bm"); D <- g("fg","t_bm"); E <- g("fg","t_fgdf")
R <- e[e$variant == "cr2", ]; R <- R[match(names(lab), R$term), ]
out <- "../manuscript/tables/supp_va_table.tex"
sink(out)
cat("% Generated by inst/application/make_supp_va_table.R -- do not edit by hand.\n")
cat("\\begin{table}[ht]\n\\centering\n\\caption{VHA application: 95\\% confidence intervals for the adjusted odds ratios under alternative variance corrections and reference distributions. All columns share the point estimates in Table~3 of the main text.}\n\\label{tab:S_va}\n\\footnotesize\\setlength{\\tabcolsep}{3pt}\n")
cat("\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}}lcccccc@{}}\n\\toprule\n")
cat("& \\multicolumn{2}{c}{Uncorrected} & KC & \\multicolumn{2}{c}{FG} & CR2\\\\\n\\cmidrule(lr){2-3}\\cmidrule(lr){4-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-7}\n")
cat("Covariate & $z$ & $t_{\\mathrm{BM}}$ & $t_{\\mathrm{BM}}$ & $t_{\\mathrm{BM}}$ & $t_{\\mathrm{FG}}$ & Satterthwaite\\\\\n\\midrule\n")
for (k in seq_along(lab)) {
  t <- names(lab)[k]
  if (t %in% names(grp)) cat(if (k > 1) "\\addlinespace\n", "\\multicolumn{7}{@{}l}{\\textit{", grp[[t]], "}}\\\\\n", sep = "")
  if (t %in% names(sub)) cat(sub[[t]], " & & & & & &\\\\\n", sep = "")
  cat(sprintf("%s & %s & %s & %s & %s & %s & %s\\\\\n", lab[k],
    ci(A[k, ]), ci(B[k, ]), ci(C[k, ]), ci(D[k, ]), ci(E[k, ]), ci(R[k, ])))
}
cat("\\bottomrule\n\\end{tabular*}\n\n\\vspace{3pt}\n\\parbox{\\textwidth}{\\footnotesize Uncorrected, VISN-clustered sandwich. KC, FG, score-space corrections. $t_{\\mathrm{BM}}$, $t$ reference on score-space Bell--McCaffrey degrees of freedom; $t_{\\mathrm{FG}}$, degrees of freedom of Fay and Graubard. CR2, bias-reduced linearization with Satterthwaite degrees of freedom computed on the pooled data with the clubSandwich package. The KC, $t_{\\mathrm{BM}}$ column is the recommended procedure. CAN, Care Assessment Need; ICU, intensive care unit; AUDIT-C, Alcohol Use Disorders Identification Test--Consumption. Reference categories: male; age 18--64 years; AUDIT-C unhealthy use or higher; no opioid use disorder; CAN score below the 60th percentile; nonfrail or prefrail; no ICU stay; medical or surgical discharging service; no addiction consult; routine discharge.}\n\\end{table}\n")
sink()
# any significance differences between columns?
sig <- function(x) x$CI_low > 1 | x$CI_high < 1
print(data.frame(term = names(lab), z = sig(A), ubm = sig(B), kc = sig(C), fg = sig(D), fgdf = sig(E), cr2 = sig(R)), row.names = FALSE)
